import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

/**
 * TS-002: flat ESLint config for Next 15 / React 19 (the app previously had
 * no eslint config at all, so `next lint` was a no-op prompt). Follows the
 * create-next-app flat-config convention: next/core-web-vitals +
 * next/typescript via FlatCompat. Rules are NOT blanket-disabled — anything
 * surfaced by the lint run is fixed in code; narrow rule configuration
 * belongs below with an inline justification comment.
 */
const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts", // generated by Next
      "public/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
