-- ============================================================================
-- seed_ddl.sql — Iceberg DDL for the platform data seeding tables
-- (SPEC-W17, Agent C; adaptation of the uploaded "Section 8" spec which named
-- Delta Lake — standing OpenDesk ruling: Iceberg, NOT Delta. See SPEC-W17
-- "Mandatory stack adaptations" #1.)
--
-- Apply with spark-sql against the `iceberg` REST catalog (same catalog the
-- W13 cac_analytics job uses), e.g.:
--
--   docker exec opendesk-spark-master /opt/bitnami/spark/bin/spark-sql \
--     --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.6.1,org.apache.iceberg:iceberg-aws-bundle:1.6.1 \
--     -f /opt/sql/iceberg/seed_ddl.sql
--
-- (bootstrap.sh step 2 runs this when the lakehouse is up, else skips with a
-- log line — the DDL is also applied lazily by the three seed_* spark jobs,
-- which call CREATE TABLE IF NOT EXISTS before writing, mirroring
-- cac_analytics.ensure_target_tables().)
--
-- Idioms mirrored from infra/lakehouse/spark/jobs/cac_analytics.py (SPEC-W13):
--   * namespaces under the `iceberg` catalog, Trino-visible;
--   * CREATE ... IF NOT EXISTS (fully idempotent, safe to re-apply);
--   * PARTITIONED BY days(...) where temporal (per SPEC-W17 Agent C contract);
--     non-temporal reference grids are identity-partitioned by state/zone so
--     reseeds can use dynamic partition overwrite (overwritePartitions)
--     exactly like the W13 gold jobs;
--   * geometry stored as WKT STRING because Iceberg has no geometry type
--     (same ruling as cac_analytics.py / geo_analytics.py).
--
-- RLS: N/A — these are platform-level SYNTHETIC reference tables in the
-- lakehouse (Iceberg), not the Postgres booking RLS tables; every row carries
-- is_synthetic = true and no tenant PII (SPEC-W17 contract C / D note).
-- ============================================================================

CREATE NAMESPACE IF NOT EXISTS iceberg.cac_silver;
CREATE NAMESPACE IF NOT EXISTS iceberg.cac_gold;

-- ----------------------------------------------------------------------------
-- cac_silver.wards — 8,812 synthetic ward rows (Agent A's seed_wards.py is the
-- Postgres source of truth in cac.wards; this Iceberg mirror is loaded by the
-- lakehouse jobs for spatial joins). Real ward lists are unavailable offline;
-- names are STABLE synthetic "Ward NN — <LGA>" (documented substitution,
-- SPEC-W17 Agent A scope / section 8.2 row 2).
-- Identity-partitioned by geopolitical zone: reseeds overwrite only the zone
-- partitions present in the input (dynamic partition overwrite).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS iceberg.cac_silver.wards (
    ward_id       STRING,      -- deterministic id (sha256 natural key, contract A)
    ward_name     STRING,      -- "Ward NN — <LGA>"
    lga_id        STRING,
    lga_name      STRING,
    state         STRING,
    zone          STRING,      -- geo-political zone (NC/NE/NW/SE/SS/SW)
    is_synthetic  BOOLEAN,     -- always true for seeded rows (contract C)
    seeded_at     TIMESTAMP
) USING iceberg
PARTITIONED BY (zone);

-- ----------------------------------------------------------------------------
-- cac_silver.geo_points — 50,000 synthetic settlement points (scaled by
-- SEED_SCALE) generated by infra/lakehouse/spark/jobs/seed_geo_points.py.
-- geom is WKT POINT(lng lat) EPSG:4326 (Iceberg has no geometry type — WKT
-- ruling per cac_analytics.py); h3_cell is the Sedona H3 res-8 cell
-- (ST_H3CellIDs, Sedona >= 1.6.0 — pinned 1.7.0, see sedona_common.py).
-- Identity-partitioned by state for idempotent per-state overwrite.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS iceberg.cac_silver.geo_points (
    point_id      STRING,      -- deterministic id
    anchor_id     STRING,      -- LGA id (or state fallback anchor) the point belongs to
    anchor_name   STRING,
    state         STRING,
    lat           DOUBLE,
    lng           DOUBLE,
    geom          STRING,      -- WKT "POINT(lng lat)", EPSG:4326
    h3_cell       BIGINT,      -- H3 res-8 cell (nullable if Sedona unavailable)
    is_synthetic  BOOLEAN,
    seeded_at     TIMESTAMP
) USING iceberg
PARTITIONED BY (state);

-- ----------------------------------------------------------------------------
-- cac_silver.coverage — synthetic radio-coverage grid, 774 LGAs x 200
-- station rows (scaled by SEED_SCALE) from seed_coverage.py. Station codes
-- NG-<STATE>-<nnn>, band FM/AM, deterministic. Synthetic substitution for a
-- real NBC station register (unavailable offline) — documented per SPEC-W17.
-- Identity-partitioned by state for idempotent per-state overwrite.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS iceberg.cac_silver.coverage (
    station_id    STRING,      -- deterministic id
    station_code  STRING,      -- NG-<STATE>-<nnn>
    lga_id        STRING,
    lga_name      STRING,
    state         STRING,
    band          STRING,      -- FM | AM
    frequency     DOUBLE,      -- MHz (FM 87.5-108.0 / AM 0.531-1.602)
    power_kw      DOUBLE,
    lat           DOUBLE,      -- transmitter site, jittered around LGA centroid
    lng           DOUBLE,
    geom          STRING,      -- WKT "POINT(lng lat)", EPSG:4326
    is_synthetic  BOOLEAN,
    seeded_at     TIMESTAMP
) USING iceberg
PARTITIONED BY (state);

-- ----------------------------------------------------------------------------
-- cac_gold.channel_unit_costs — 32 channels x 24 months of synthetic unit-cost
-- rows in NGN (deterministic pseudo-random walk per channel; no real crawling
-- offline — documented substitution). Loaded from Agent A's JSON manifest by
-- seed_gold_load.py. Temporal: partitioned by days(month) per SPEC-W17.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS iceberg.cac_gold.channel_unit_costs (
    month         DATE,        -- first of month
    channel_code  STRING,
    channel_name  STRING,
    channel_class STRING,      -- above-the-line | below-the-line
    unit_cost_ngn DOUBLE,      -- cost per acquisition-relevant unit, NGN
    currency      STRING,      -- 'NGN'
    is_synthetic  BOOLEAN,
    seeded_at     TIMESTAMP
) USING iceberg
PARTITIONED BY (days(month));

-- ----------------------------------------------------------------------------
-- cac_gold.usd_shadow_prices — USD/NGN daily series, 5 years, anchored random
-- walk ~N410 (2021-08) to ~N1,550 (2026-08 regime) with official/parallel
-- spread. Generated by Agent B's seed_fx.py (plain Python — Langflow dropped,
-- SPEC-W17 adaptation #4), loaded from its Iceberg-side JSON manifest by
-- seed_gold_load.py. Temporal: partitioned by days(day).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS iceberg.cac_gold.usd_shadow_prices (
    day           DATE,
    official_ngn  DOUBLE,      -- official USD/NGN rate
    parallel_ngn  DOUBLE,      -- parallel ("shadow") market rate
    shadow_mid    DOUBLE,      -- mid of official/parallel
    spread_bps    DOUBLE,      -- (parallel - official) / official * 1e4
    is_synthetic  BOOLEAN,
    seeded_at     TIMESTAMP
) USING iceberg
PARTITIONED BY (days(day));

-- ----------------------------------------------------------------------------
-- cac_gold.seed_run_log — one row per seed run per table (lakehouse-side
-- mirror of Postgres cac.seed_run_log, contract A log_seed_run). Temporal:
-- partitioned by days(seeded_at).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS iceberg.cac_gold.seed_run_log (
    run_id        STRING,      -- deterministic id: sha256(salt|table|git_sha|runner_id)
    table_name    STRING,
    rowcount      BIGINT,
    runner_id     STRING,
    git_sha       STRING,
    seed_scale    DOUBLE,
    status        STRING,      -- ok | dry-run | failed
    seeded_at     TIMESTAMP
) USING iceberg
PARTITIONED BY (days(seeded_at));
